import './globals.css'
import { ClusterProvider } from '@/components/cluster/cluster-data-access'
import { SolanaProvider } from '@/components/solana/solana-provider'
import { Toaster, toast } from 'sonner'
import { UiLayout } from '@/components/ui/ui-layout'
import { ReactQueryProvider } from './react-query-provider'
import { NextUIProvider } from "@nextui-org/react";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import { JupiterWalletProvider } from '@/components/solana/unified-wallet-provider'
import { DayPickerProvider } from 'react-day-picker'

export const metadata = {
  title: 'vesting',
  description: 'Generated by create-solana-dapp',
}

// const links: { label: string; path: string }[] = [
//   { label: 'Account', path: '/account' },
//   { label: 'Clusters', path: '/clusters' },
//   { label: 'Vesting Program', path: '/vesting' },
// ]

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`dark ${GeistSans.className}`}>
      <body>
        <ReactQueryProvider>
        
          <ClusterProvider>
            <SolanaProvider>
            {/* <JupiterWalletProvider> */}
              {/* <UiLayout links={links}> */}
              <NextUIProvider>
                {/* <DayPickerProvider> */}
                {children}
                {/* </DayPickerProvider> */}
                <Toaster position="bottom-right" />
              </NextUIProvider>
              {/* </JupiterWalletProvider> */}
                {/* </UiLayout> */}
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
